### ISSUE TITLE
Symfony/Config 3.x

### ISSUE THREAD

**Issue by gander** [flint/tacker#10]
_Catchable fatal error: Object of class Symfony\Component\Config\ConfigCache could not be converted to string in vendor/flint/tacker/src/Tacker/Loader/CacheLoader.php on line 58_

require:
`"symfony/config" : ">=2.3"`
should be:
`"symfony/config" : "^2.3"`

**Comment by henrikbjorn** [comment]
Apparently they changed the whole config component for 3.0. We should fix our usage of it.

**Comment by kanafghan** [comment]
+1

**Comment by henrikbjorn** [comment]
I think this was fixed here https://github.com/flint/tacker/blob/master/src/Loader/CacheLoader.php#L61

**Comment by toin0u** [comment]
@henrikbjorn yes it was fixed there but I think @gander uses the the version 0.6.1 (https://github.com/flint/tacker/blob/0.6.1/src/Tacker/Loader/CacheLoader.php#L58) which does not have the fix. Maybe a 0.6.2 could be released with it?

**Comment by henrikbjorn** [comment]
Feel free to open a Pull Request with the change for the 0.x branch.

Why not upgrade to the 1.x relases?

**Comment by toin0u** [comment]
I think it's because @gander uses flint 1.x isn't it?

**Comment by gander** [comment]
I don't remember, what I am using. But, when I am looking at time when my issue started, the latest stable version of `flint/flint` at that day was `1.7.1` and required for this package version of `flint/tacker` (`~0.4`) was `0.6.0`. ;)

**Comment by toin0u** [comment]
@gander yes exactly :)
