### ISSUE TITLE
Recursively resolve options in configuration file

### ISSUE THREAD

**Issue by alcohol** [flint/tacker#5]
If my configuration looks like:

```
kernel.env: "#KERNEL_ENV#"
monolog.logfile: "%root_dir%/logs/%kernel.env%.log"
```

I would like/expect `kernel.env` to be available (e.g. can be referenced) by all subsequent option definitions. The only constraint being of course that options can only refer to previously defined options (so order of definitions is relevant).

Not sure if this properly describes what I mean, fingers crossed.

**Comment by mediamonks-robert** [comment]
+1

**Comment by henrikbjorn** [comment]
Would you be able to write a test case for this?
