### ISSUE TITLE
Merge multiple configs

### ISSUE THREAD

**Issue by mediamonks-robert** [flint/tacker#6]
I expect options to be merged instead of being overwritten:

*config.yml*

    php:
        timezone: "UTC"
        error_reporting: 0
        ini:
            display_errors: false
            display_startup_errors: false

*config_development.yml*

    php:
        error_reporting: -1
        ini:
            display_errors: true
            display_startup_errors: true

Expected result:

$app['php']['timezone'] contains "UTC"

Actual results:

$app['php']['timezone'] does not exist

**Comment by henrikbjorn** [comment]
This is currently not possible. Symfony does this by having a configuration setting per configuration tree.

Sorry this wont happen.
