### ISSUE TITLE
Symfony/Yaml 3.x

### ISSUE THREAD

**Issue by gander** [flint/tacker#9]
_The ability to pass file names to the \Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead._

require-dev:
`"symfony/yaml" : "~2.2"`
should be:
`"symfony/yaml" : "^2.2"`

**Comment by henrikbjorn** [comment]
Fixed in 0.6.1
